# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{table_fu}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Percival"]
  s.date = %q{2009-10-08}
  s.description = %q{A library for manipulating tables as arrays}
  s.email = %q{mark@mpercival.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/table_fu.rb",
     "lib/table_fu/formatting.rb",
     "spec/assets/sample.csv",
     "spec/assets/test.csv",
     "spec/assets/test_macro.csv",
     "spec/rcov.opts",
     "spec/readme_example_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/table_fu_spec.rb"
  ]
  s.homepage = %q{http://github.com/markpercival/table_fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TableFu makes arrays act like spreadsheets}
  s.test_files = [
    "spec/readme_example_spec.rb",
     "spec/spec_helper.rb",
     "spec/table_fu_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<spec>, [">= 0"])
    else
      s.add_dependency(%q<spec>, [">= 0"])
    end
  else
    s.add_dependency(%q<spec>, [">= 0"])
  end
end
